---
image: python:3

services:
 - docker:dind

variables:
 DOCKER_HOST: 'tcp://docker:2375'

stages:
  - build

before_script:
  - apt -qq update && apt install -y docker.io
  - pip install ansible==2.9.6 molecule==2.22 docker==4.2.0

ansible_build:
  stage: build
  script:
    - molecule test
